[window]
opacity = 0.6
padding.x = 10
padding.y = 10
[font]
size = 12.0
[font.normal]
family = "JetBrainsMonoNL NF"

[general]
import = [ "~/.config/alacritty/themes/themes/gruvbox_dark.toml" ]

[bell]
duration = 0
